# Generated by Django 4.0.1 on 2024-06-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0006_alter_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
